from .companies import router as companies_router
from .branches import router as branches_router
from .usertypes import router as usertypes_router
from .modules import router as modules_router
from .designations import router as designations_router
#from .students import router as students_router
from .lms_users import router as users_router
from .demoform import router as demo_router
from .parents import router as parents_router
from .stdnt_contact_info import router as students_contact_router
from .student_educations import router as students_educations_router
from .subjects import router as subjects_router
from .lessons import router as lessons_router
from .courses import router as courses_router
from .demovideos import router as demovideos_router
from .standards import router as standards_router
from .std_profile import router as admission_router
from .inquiry_form import router as inquiry_router
from .batches import router as batches_router
from .fees import router as fees_router
#from .payment_status import router as payment_router
from .Questions import router as questions_router
from .Test import router as tests_router
from .fees import router as fees_router
from .payments import router as payments_router
from .installments import router as installments_router
from .Question_Paper_Table import router as question_papers_router
from .Question_Paper import router as question_mappings_router
from .paper import router as papers_router
from .contents import router as content_router
from .Test import router as tests_router
#from .Teacher import router as teachers_router
#from .students import router as students_router
#from ...Teacher_data.Employee.api.employee_master_table import router as employees_router

from .teacher_profile import router as teachers_Data_router
from .mail import router as mail_router
