from .companies import router as companies_router
from .branches import router as branches_router
from .usertypes import router as usertypes_router
from .modules import router as modules_router
from .designations import router as designations_router
from .students import router as students_router
from .lms_users import router as users_router
from .demoform import router as demo_router
from .parents import router as parents_router
from .stdnt_contact_info import router as students_contact_router
from .student_educations import router as students_educations_router
from .subjects import router as subjects_router
from .courses import router as courses_router
from .demovideos import router as demovideos_router
from .standards import router as standards_router
from .std_profile import router as admission_router
from .inquiry_form import router as inquiry_router
from .payment_status import router as payment_router
