from .company import Company
from .branch import Branch
from .usertype import UserType
from .module import Module
from .designation import Designation
from .Students import Student
from .user import LmsUsers
from .demoformfill import DemoFormFill
from .parents_info import Parent
from .students_contact_info import ContactInformation
from .student_education import PreEducation
from .course import Course
from .subject import Subject
from .demovideo import Video
from .standard import Standard
from .inquiry import Inquiry
from .course_detail import CourseDetails
from .fee import Fee
from .batch import Batch
from .content import Content
from .lesson import Lesson
from .payment import Payment
from .installment import Installment
from .content import Content
from .Teacher import Teacher
from .Students import Student
from .teacher_contact_info import TeacherContact
from .teacher_education import Education
from .teacher_skills import Skill
from .teacher_lang_knowledge import LanguagesSpoken
from .teacher_emergency_contact import EmergencyContact
from .teacher_depends import Dependents
from .employee_master_table import Employee
from .mail import Mail
from .announcement import Announcement
from .teacher_course import TeacherCourse
from .courses_content import Course_content
from .attendance import Attendance
from .Discount_Ass_result import DiscountAssessmentResut
from .Discount_assesment_paper import DiscountQuestion
from .lesson_test_paper import QuestionPaper1
from .lesson_student_test_ans import StudentAnswer
from .lesson_test_question import LessontestQuestion