from .company import Company
from .branch import Branch
from .usertype import UserType
from .module import Module
from .designation import Designation
from .Students import Student
from .user import LmsUsers
from .demoformfill import DemoFormFill
from .parents_info import Parent
from .students_contact_info import ContactInformation
from .student_education import PreEducation
from .course import Course
from .subject import Subject
from .demovideo import Video
from .standard import Standard
from .inquiry import Inquiry
from .payment import PaymentStatus
from .course_detail import CourseDetails
